[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons
default_productivity_apps = True
admin_passwd = $pbkdf2-sha512$600000$Y0yplZLy/n8PYUyptXZubQ$HvYcQ2ZyamRGzX6bRWyqvi/0ZfY25gqlgaACLc53v7iUC9pNEnWDiow7jESthZOae7eZ6vZDWiKPePU315N4Lg

